site_name: IronBars
site_description: Intelligent Data Visualization & EDA Assistant
site_author: Sahil Gour aka Sevrus

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Change Log: changelog.md
  - API Reference: api.md
  - Usage Guide: usage.md

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
  - tables

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src", "docs"]